---
version: 1
dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN pip install 'ansible-lint>=5.3.2'
    - RUN pip install molecule
