---
version: 1
dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt
  # wheel deps should be used only for packages that are not available as rpms
  python: _build/requirements.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
