name: release
on:
  release:
    types:
      - published
  workflow_dispatch:
permissions: {}

jobs:
  task:
    name: ${{ matrix.command }}
    runs-on: ubuntu-22.04
    environment:
      name: release

    strategy:
      fail-fast: false
      matrix:
        command:
          - release
    steps:
      - name: Grab the source from Git
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # needed to determine version

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          # keep this in sync with python version from base container
          python-version: "3.10" # 3.10 is default on ubuntu-22.04
          cache: "pip"

      - name: "Run: task ${{ matrix.command }}"
        run: task ${{ matrix.command }}
